# Generated by Django 3.2.6 on 2021-09-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('partner', models.CharField(max_length=500, unique=True)),
                ('period', models.SlugField(max_length=255, unique=True)),
                ('price', models.IntegerField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='promotion')),
                ('logo', models.ImageField(blank=True, upload_to='promotion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'ข้อมูลสินค้า',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'หมวดหมู่สินค้า', 'verbose_name_plural': 'ข้อมูลประเภทสินค้า'},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.category'),
        ),
    ]
