# Generated by Django 3.2.6 on 2021-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20210914_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='period',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
