# Generated by Django 3.2.6 on 2021-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_promotion_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
