# Generated by Django 3.2.6 on 2021-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promotion_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='id',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
