# Generated by Django 3.2.6 on 2021-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_auto_20210914_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('Phone_namber', models.CharField(max_length=12, unique=True)),
                ('ID_card', models.CharField(max_length=13, unique=True)),
                ('address', models.TimeField()),
                ('ZIP_code', models.CharField(max_length=6, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
