# Generated by Django 3.2.6 on 2021-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ('username',), 'verbose_name': 'สมาชิกรับหิ้ว', 'verbose_name_plural': 'ข้อมูลสมาชิกรับหิ้ว'},
        ),
        migrations.AlterField(
            model_name='register',
            name='ZIP_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(),
        ),
    ]
