# Generated by Django 3.2.6 on 2021-09-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_auto_20210926_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Registers',
        ),
    ]
