# Generated by Django 3.2.6 on 2021-09-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0010_registers_p_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registers',
            old_name='p_play',
            new_name='Prompt_Pay',
        ),
    ]
