# Generated by Django 3.2.6 on 2021-09-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0011_rename_p_play_registers_prompt_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recom',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('partner_link', models.TextField(blank=True)),
                ('period', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='promotion')),
                ('logo', models.ImageField(blank=True, upload_to='promotion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.category')),
            ],
            options={
                'verbose_name': 'สินค้าแนะนำ',
                'verbose_name_plural': 'ข้อมูลสินค้าแนะนำ',
                'ordering': ('name',),
            },
        ),
    ]
