# Generated by Django 3.2.6 on 2021-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0014_auto_20210927_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recom',
            name='price',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recom',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
