# Generated by Django 3.2.6 on 2021-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0016_auto_20210927_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre_order',
            options={'ordering': ('name',), 'verbose_name': 'สินค้ารับหิ้ว', 'verbose_name_plural': 'ข้อมูลสินค้าหน้ารับหิ้ว'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ('name',), 'verbose_name': 'สินค้า', 'verbose_name_plural': 'ข้อมูลสินค้าโปรโมชั่น'},
        ),
        migrations.AddField(
            model_name='slides',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
