# Generated by Django 3.2.6 on 2021-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0017_auto_20210927_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_order',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
