# Generated by Django 3.2.6 on 2021-09-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0019_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'ตะกร้าสินค้า', 'verbose_name_plural': 'ข้อมูลตะกร้าสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='registers',
            options={'verbose_name': 'สมาชิกรับหิ้ว', 'verbose_name_plural': 'ข้อมูลสมาชิกรับหิ้ว'},
        ),
        migrations.AddField(
            model_name='pre_order',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
