# Generated by Django 3.2.6 on 2021-09-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0021_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, upload_to='preorder'),
        ),
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.CharField(default='สาขาที่ขาย', max_length=255),
        ),
    ]
