# Generated by Django 3.2.6 on 2021-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0026_auto_20211003_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('Phone_namber', models.CharField(max_length=12, unique=True)),
                ('Prompt_Pay', models.CharField(default='0123456789999', max_length=13, unique=True)),
                ('ID_card', models.CharField(max_length=13, unique=True)),
                ('address', models.TextField()),
                ('ZIP_code', models.CharField(max_length=6)),
                ('active', models.BooleanField(default=False)),
                ('orderId', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายการรับหิ้ว',
                'verbose_name_plural': 'รายการของสมาชิกรับหิ้ว',
            },
        ),
    ]
