# Generated by Django 3.2.6 on 2021-10-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0027_orderpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpartner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
