# Generated by Django 3.2.6 on 2021-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0028_alter_orderpartner_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpartner',
            name='ID_card',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='orderpartner',
            name='Phone_namber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orderpartner',
            name='Prompt_Pay',
            field=models.CharField(default='0123456789999', max_length=13),
        ),
        migrations.AlterField(
            model_name='orderpartner',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpartner',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
