# Generated by Django 3.2.6 on 2021-10-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0029_auto_20211003_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpartner',
            options={'verbose_name': 'รายการรับหิ้ว', 'verbose_name_plural': 'รายการรับหิ้ว'},
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partneruser', models.CharField(max_length=100)),
                ('partneremail', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.order')),
            ],
            options={
                'db_table': 'OrderDetail',
                'ordering': ('id',),
            },
        ),
    ]
