# Generated by Django 3.2.6 on 2021-10-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0030_auto_20211004_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpartner',
            options={'ordering': ('orderId',), 'verbose_name': 'รายการรับหิ้ว', 'verbose_name_plural': 'รายการรับหิ้ว'},
        ),
    ]
